QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CompilerIdC/CMakeCCompilerId.c \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CompilerIdCXX/CMakeCXXCompilerId.cpp \
    ../../../Udacity/git/controls_cpp/src/BaseController.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/ColorUtils.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/DrawingFuncs.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/GLUTMenu.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/Graph.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/GraphManager.cpp \
    ../../../Udacity/git/controls_cpp/src/Drawing/Visualizer_GLUT.cpp \
    ../../../Udacity/git/controls_cpp/src/Math/Geometry.cpp \
    ../../../Udacity/git/controls_cpp/src/Math/Random.cpp \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/MavlinkNode.cpp \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/MavlinkTranslation.cpp \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/PracticalSocket.cpp \
    ../../../Udacity/git/controls_cpp/src/QuadControl.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/BaseDynamics.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/QuadDynamics.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/Simulator.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/magnetometer.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/opticalflow.cpp \
    ../../../Udacity/git/controls_cpp/src/Simulation/rangefinder.cpp \
    ../../../Udacity/git/controls_cpp/src/Trajectory.cpp \
    ../../../Udacity/git/controls_cpp/src/Utility/Camera.cpp \
    ../../../Udacity/git/controls_cpp/src/Utility/SimpleConfig.cpp \
    ../../../Udacity/git/controls_cpp/src/Utility/Timer.cpp \
    ../../../Udacity/git/controls_cpp/src/main.cpp \
    main.cpp \
    mainwindow.cpp

HEADERS += \
    ../../../Udacity/git/controls_cpp/lib/freeglut/include/GL/freeglut.h \
    ../../../Udacity/git/controls_cpp/lib/freeglut/include/GL/freeglut_ext.h \
    ../../../Udacity/git/controls_cpp/lib/freeglut/include/GL/freeglut_std.h \
    ../../../Udacity/git/controls_cpp/lib/freeglut/include/GL/glut.h \
    ../../../Udacity/git/controls_cpp/lib/matrix/AxisAngle.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Dcm.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Euler.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Matrix.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Quaternion.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Scalar.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/SquareMatrix.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Vector.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Vector2.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/Vector3.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/filter.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/helper_functions.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/integration.hpp \
    ../../../Udacity/git/controls_cpp/lib/matrix/math.hpp \
    ../../../Udacity/git/controls_cpp/lib/mavlink/checksum.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/common.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_actuator_control_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_adsb_vehicle.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_altitude.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_att_pos_mocap.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_attitude.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_attitude_quaternion.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_attitude_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_auth_key.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_autopilot_version.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_battery_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_button_change.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_camera_capture_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_camera_image_captured.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_camera_information.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_camera_settings.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_camera_trigger.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_change_operator_control.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_change_operator_control_ack.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_collision.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_command_ack.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_command_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_command_long.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_control_system_state.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_data_stream.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_data_transmission_handshake.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_debug.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_debug_vect.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_distance_sensor.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_encapsulated_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_estimator_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_extended_sys_state.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_file_transfer_protocol.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_flight_information.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_follow_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_global_position_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_global_position_int_cov.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps2_raw.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps2_rtk.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_global_origin.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_inject_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_input.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_raw_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_rtcm_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_rtk.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_gps_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_heartbeat.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_high_latency.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_high_latency2.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_highres_imu.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_actuator_controls.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_controls.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_gps.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_optical_flow.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_sensor.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_state.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_hil_state_quaternion.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_home_position.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_landing_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_local_position_ned.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_local_position_ned_cov.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_entry.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_erase.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_request_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_request_end.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_log_request_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_logging_ack.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_logging_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_logging_data_acked.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_manual_control.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_manual_setpoint.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_memory_vect.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_message_interval.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_ack.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_clear_all.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_count.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_current.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_item.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_item_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_item_reached.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_request.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_request_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_request_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_request_partial_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_set_current.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mission_write_partial_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_mount_orientation.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_named_value_float.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_named_value_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_nav_controller_output.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_obstacle_distance.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_optical_flow.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_optical_flow_rad.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_ext_ack.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_ext_request_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_ext_request_read.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_ext_set.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_ext_value.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_map_rc.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_request_list.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_request_read.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_set.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_param_value.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_ping.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_play_tune.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_position_target_global_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_position_target_local_ned.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_power_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_protocol_version.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_radio_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_raw_imu.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_raw_pressure.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_rc_channels.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_rc_channels_override.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_rc_channels_raw.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_rc_channels_scaled.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_request_data_stream.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_resource_request.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_safety_allowed_area.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_imu.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_imu2.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_imu3.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_pressure.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_pressure2.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_scaled_pressure3.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_serial_control.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_servo_output_raw.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_actuator_control_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_attitude_target.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_gps_global_origin.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_home_position.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_mode.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_position_target_global_int.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_set_video_stream_settings.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_setup_signing.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_sim_state.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_statustext.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_storage_information.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_sys_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_system_time.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_terrain_check.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_terrain_data.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_terrain_report.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_terrain_request.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_timesync.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_uavcan_node_info.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_uavcan_node_status.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_v2_extension.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_vfr_hud.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_vibration.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_vicon_position_estimate.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_video_stream_information.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_vision_position_estimate.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_vision_speed_estimate.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_wifi_config_ap.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/mavlink_msg_wind_cov.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/testsuite.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/common/version.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/mavlink_conversions.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/mavlink_get_info.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/mavlink_helpers.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/mavlink_sha256.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/mavlink_types.h \
    ../../../Udacity/git/controls_cpp/lib/mavlink/protocol.h \
    ../../../Udacity/git/controls_cpp/src/BaseController.h \
    ../../../Udacity/git/controls_cpp/src/Common.h \
    ../../../Udacity/git/controls_cpp/src/ControllerFactory.h \
    ../../../Udacity/git/controls_cpp/src/DataSource.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/AbsThreshold.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/BaseAnalyzer.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/ColorUtils.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/DrawingFuncs.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/GLUTMenu.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/Graph.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/GraphManager.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/Visualizer_GLUT.h \
    ../../../Udacity/git/controls_cpp/src/Drawing/WindowThreshold.h \
    ../../../Udacity/git/controls_cpp/src/Math/Angles.h \
    ../../../Udacity/git/controls_cpp/src/Math/Constants.h \
    ../../../Udacity/git/controls_cpp/src/Math/Geometry.h \
    ../../../Udacity/git/controls_cpp/src/Math/LowPassFilter.h \
    ../../../Udacity/git/controls_cpp/src/Math/Mat3x3F.h \
    ../../../Udacity/git/controls_cpp/src/Math/MathUtils.h \
    ../../../Udacity/git/controls_cpp/src/Math/Quaternion.h \
    ../../../Udacity/git/controls_cpp/src/Math/Random.h \
    ../../../Udacity/git/controls_cpp/src/Math/Transform3D.h \
    ../../../Udacity/git/controls_cpp/src/Math/V3D.h \
    ../../../Udacity/git/controls_cpp/src/Math/V3F.h \
    ../../../Udacity/git/controls_cpp/src/Math/V4D.h \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/MavlinkNode.h \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/MavlinkTranslation.h \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/PracticalSocket.h \
    ../../../Udacity/git/controls_cpp/src/MavlinkNode/UDPPacket.h \
    ../../../Udacity/git/controls_cpp/src/QuadControl.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/BaseDynamics.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/QuadDynamics.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/Simulator.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/magnetometer.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/opticalflow.h \
    ../../../Udacity/git/controls_cpp/src/Simulation/rangefinder.h \
    ../../../Udacity/git/controls_cpp/src/Trajectory.h \
    ../../../Udacity/git/controls_cpp/src/Utility/Camera.h \
    ../../../Udacity/git/controls_cpp/src/Utility/FastDelegate.h \
    ../../../Udacity/git/controls_cpp/src/Utility/FixedQueue.h \
    ../../../Udacity/git/controls_cpp/src/Utility/Mutex.h \
    ../../../Udacity/git/controls_cpp/src/Utility/SimpleConfig.h \
    ../../../Udacity/git/controls_cpp/src/Utility/StringUtils.h \
    ../../../Udacity/git/controls_cpp/src/Utility/Timer.h \
    ../../../Udacity/git/controls_cpp/src/VehicleDatatypes.h \
    mainwindow.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

SUBDIRS += \
    ../../../Udacity/git/controls_cpp/project/CPPSim.pro

DISTFILES += \
    ../../../Udacity/git/controls_cpp/CMakeLists.txt \
    ../../../Udacity/git/controls_cpp/README.md \
    ../../../Udacity/git/controls_cpp/animations/scenario1.gif \
    ../../../Udacity/git/controls_cpp/animations/scenario2.gif \
    ../../../Udacity/git/controls_cpp/animations/scenario3.gif \
    ../../../Udacity/git/controls_cpp/animations/scenario4.gif \
    ../../../Udacity/git/controls_cpp/animations/scenario5.gif \
    ../../../Udacity/git/controls_cpp/build-CPPSim-Desktop-Debug/CPPSim \
    ../../../Udacity/git/controls_cpp/build/CMakeCache.txt \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CMakeCCompiler.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CMakeCXXCompiler.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CMakeDetermineCompilerABI_C.bin \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CMakeDetermineCompilerABI_CXX.bin \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CMakeSystem.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CompilerIdC/a.out \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/3.19.4/CompilerIdCXX/a.out \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CMakeDirectoryInformation.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CMakeOutput.log \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/CXX.includecache \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/DependInfo.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/build.make \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/cmake_clean.cmake \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/depend.internal \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/depend.make \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/flags.make \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/link.txt \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/CPPSim.dir/progress.make \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/TargetDirectories.txt \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/cmake.check_cache \
    ../../../Udacity/git/controls_cpp/build/CMakeFiles/progress.marks \
    ../../../Udacity/git/controls_cpp/build/CPPSim \
    ../../../Udacity/git/controls_cpp/build/cmake_install.cmake \
    ../../../Udacity/git/controls_cpp/config/1_Intro.txt \
    ../../../Udacity/git/controls_cpp/config/2_AttitudeControl.txt \
    ../../../Udacity/git/controls_cpp/config/3_PositionControl.txt \
    ../../../Udacity/git/controls_cpp/config/4_Nonidealities.txt \
    ../../../Udacity/git/controls_cpp/config/5_TrajectoryFollow.txt \
    ../../../Udacity/git/controls_cpp/config/LastScenario.txt \
    ../../../Udacity/git/controls_cpp/config/QuadControlParams.txt \
    ../../../Udacity/git/controls_cpp/config/QuadPhysicalParams.txt \
    ../../../Udacity/git/controls_cpp/config/Scenarios.txt \
    ../../../Udacity/git/controls_cpp/config/Simulation.txt \
    ../../../Udacity/git/controls_cpp/config/X_Scenarios.txt \
    ../../../Udacity/git/controls_cpp/config/X_TestManyQuads.txt \
    ../../../Udacity/git/controls_cpp/config/X_TestMavlink.txt \
    ../../../Udacity/git/controls_cpp/config/traj/CircleNoFF.txt \
    ../../../Udacity/git/controls_cpp/config/traj/FigureEight.txt \
    ../../../Udacity/git/controls_cpp/config/traj/FigureEightFF.txt \
    ../../../Udacity/git/controls_cpp/config/traj/HelixNoFF.txt \
    ../../../Udacity/git/controls_cpp/config/traj/HelixUpDownNoFF.txt \
    ../../../Udacity/git/controls_cpp/config/traj/MakeCircleTrajectory.py \
    ../../../Udacity/git/controls_cpp/config/traj/MakeHelixTrajectory.py \
    ../../../Udacity/git/controls_cpp/config/traj/MakeHelixUpDownTrajectory.py \
    ../../../Udacity/git/controls_cpp/config/traj/MakePeriodicTrajectory.py \
    ../../../Udacity/git/controls_cpp/config/traj/MakeSpiralTrajectory.py \
    ../../../Udacity/git/controls_cpp/config/traj/Origin.txt \
    ../../../Udacity/git/controls_cpp/config/traj/SpiralNoFF.txt \
    ../../../Udacity/git/controls_cpp/lib/freeglut/Copying.txt \
    ../../../Udacity/git/controls_cpp/lib/freeglut/Readme.txt \
    ../../../Udacity/git/controls_cpp/lib/freeglut/bin/freeglut.dll \
    ../../../Udacity/git/controls_cpp/lib/freeglut/bin/x64/freeglut.dll \
    ../../../Udacity/git/controls_cpp/lib/freeglut/lib/freeglut.lib \
    ../../../Udacity/git/controls_cpp/lib/freeglut/lib/x64/freeglut.lib \
    ../../../Udacity/git/controls_cpp/lib/matrix/LICENSE \
    ../../../Udacity/git/controls_cpp/notes/Comparing Trajectories.ipynb \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/CODEOWNERS \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/ControlStructure.png \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/NOTES.md \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/README.md \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/controller.py \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/controls_flyer.py \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/frame_utils.py \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/setup.cfg \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/test_trajectory.txt \
    ../../../Udacity/git/controls_cpp/notes/FCND-Controls/unity_drone.py \
    ../../../Udacity/git/controls_cpp/project/FCND-CPPSim.xcodeproj/project.pbxproj \
    ../../../Udacity/git/controls_cpp/project/FCND-CPPSim.xcodeproj/project.xcworkspace/contents.xcworkspacedata \
    ../../../Udacity/git/controls_cpp/project/Simulator.sln \
    ../../../Udacity/git/controls_cpp/project/Simulator.vcxproj \
    ../../../Udacity/git/controls_cpp/project/Simulator.vcxproj.filters \
    ../../../Udacity/git/controls_cpp/x64.png
